/* Money — merged Finance + Business (cash, bills, payouts, deposits, expenses, profit) */
(function () {
  const { ico, esc, aed, st, S, save, toast, render, go, drawer, closeDrawer, modal, closeModal, PKL } = PWA;
  const tbl = (...a) => PWA.tbl(...a);

  const TX = [
    ['29 Sep', 'PAY-8912', 'Aisha Al Mansoori', 'Rent · cheque 1 of 2', 'in', 60000, 'Received', 'Spaces', 'Dubai Marina'],
    ['28 Sep', 'JOB-5521', 'Hamdan Villa', 'Deep cleaning', 'in', 900, 'Received', 'Services', 'Dubai'],
    ['27 Sep', 'PAY-8901', 'Layla Rahman', 'Rent + deposit', 'in', 30000, 'Received', 'Spaces', 'Dubai Marina'],
    ['27 Sep', 'BIL-441', 'CoolTech LLC', 'AC repair · A-0803', 'out', 1850, 'Awaiting approval', 'Spaces', 'Dubai Marina'],
    ['26 Sep', 'UPN-0926', 'UpNow', 'OS + marketplace', 'out', 1500, 'Launch credit', 'All', 'All'],
    ['25 Sep', 'REF-104', 'Priya Menon', 'Deposit refund', 'out', 6000, 'Paid', 'Spaces', 'Business Bay'],
    ['24 Sep', 'BKG-7710', 'Sofia Rossi', 'Holiday stay · 4 nights', 'in', 2600, 'Received', 'Spaces', 'Downtown'],
    ['23 Sep', 'PAY-8870', 'Omar Hassan', 'Rent · cheque 2 of 4', 'in', 29500, 'Bounced', 'Spaces', 'Dubai Marina'],
    ['22 Sep', 'BIL-438', 'Sparkle Facilities', 'Move-out clean · B-0602', 'out', 650, 'Paid', 'Spaces', 'Dubai Marina'],
    ['21 Sep', 'PAYOUT-39', 'Greenstone bank •••4410', 'Weekly payout', 'out', 142300, 'Paid', 'All', 'All']
  ];
  const ACTN = [
    ['risk', 'Bounced cheque · Omar Hassan', 'AED 29,500 · cheque 2 of 4 · Marina Gate 1807', 'Send notice', 'Formal notice drafted and sent to Omar via WhatsApp + email'],
    ['warn', '17 rent payments overdue', 'AED 88,400 across 12 customers · oldest 9 days', 'Send reminders', 'Reminders sent to 12 customers'],
    ['warn', 'CoolTech bill awaiting approval', 'AED 1,850 · AC repair A-0803 · evidence attached', 'Approve', 'Bill approved · scheduled for Wednesday payout run'],
    ['warn', '3 refunds need approval', 'AED 8,200 · deposit settlements after move-out', 'Review', 'Refund review opened'],
    ['info', 'Invoice INV-2026-0412 failed to send', 'Hassan Ali · email bounced', 'Resend by WhatsApp', 'Invoice resent via WhatsApp']
  ];
  const WEEKS = [['5 Oct', 212, 64], ['12 Oct', 148, 71], ['19 Oct', 96, 58], ['26 Oct', 184, 142], ['2 Nov', 238, 66], ['9 Nov', 121, 60], ['16 Nov', 88, 74], ['23 Nov', 176, 69]];
  const PROFIT = [
    ['Avenue Residence · 2 BR', 'Apartment', '../img/apt1.jpg', 486000, 142000], ['Palm Jumeirah beach villa', 'Holiday stay', '../img/villa1.jpg', 214000, 96000],
    ['Marina Gate · 1 BR', 'Apartment', '../img/apt3.jpg', 190000, 61000], ['Deep cleaning', 'Cleaning', '../img/clean1.jpg', 58400, 31200],
    ['Al Quoz padel court', 'Padel court', '../img/padel1.jpg', 41200, 14800], ['AC servicing', 'AC maintenance', '../img/ac1.jpg', 22600, 12900],
    ['Marina rooftop venue', 'Venue', '../img/venue1.jpg', 36000, 29500]
  ];
  const TABS = ['Overview', 'Transactions', 'Invoices', 'Bills', 'Payouts', 'Deposits', 'Expenses', 'Profit & loss'];

  const filt = () => `<div class="fbar" style="margin:0"><select class="msel" id="mfB"><option>All branches</option><option>Dubai Marina</option><option>Business Bay</option><option>Downtown</option></select><select class="msel"><option>All packs</option><option>Spaces</option><option>Services</option></select><select class="msel"><option>Last 30 days</option><option>This quarter</option><option>This year</option></select><span class="sp"></span><button class="btn btn-o btn-sm" data-act="toastX" data-arg="CSV exported">Export</button></div>`;
  const stK = s => /Bounced|Overdue/.test(s) ? 'risk' : /Awaiting|Due|Pending|Draft/.test(s) ? 'warn' : /credit/.test(s) ? 'info' : '';

  function overview() {
    const mx = Math.max(...WEEKS.flatMap(w => [w[1], w[2]]));
    const P = PROFIT.map(p => [...p, p[3] - p[4], (p[3] - p[4]) / p[3]]).sort((a, b) => b[5] - a[5]);
    return `<div class="g4">${[['Coming in · next 30 days', 'AED 640k', '212 payments scheduled', ''], ['Next payout', 'AED 184,600', 'Wed 30 Sep · to •••4410', ''], ['You owe', 'AED 65,750', 'Suppliers 64,250 · UpNow 1,500', 'warn'], ['Deposits held', 'AED 520,000', '103 customers · protected', '']].map(k => `<div class="kpi" style="cursor:default"><small>${k[0]}</small><b style="font-size:26px">${k[1]}</b><span class="d" style="color:${k[3] ? 'var(--amber)' : 'var(--ink3)'}">${k[2]}</span></div>`).join('')}</div>
    <div class="gd mt"><section class="pn"><div class="pn-h"><h2>Needs action</h2><span class="sub">${ACTN.length} items</span></div>
      ${ACTN.map((a, i) => `<div class="ar" id="ma${i}"><span class="st ${a[0]}" style="width:10px;padding:0;height:10px"></span><div class="bd"><b>${esc(a[1])}</b><small>${esc(a[2])}</small></div><button class="btn ${a[0] === 'risk' ? 'btn-g' : 'btn-o'} btn-sm" data-act="mAct" data-arg="${i}">${esc(a[3])}</button></div>`).join('')}</section>
    <section class="pn"><div class="pn-h"><h2>Cash flow</h2><span class="sub">Next 8 weeks · AED k</span><span class="sp"></span><span class="lgd"><i style="background:var(--g6)"></i>In <i style="background:#e9b872;margin-left:8px"></i>Out</span></div>
      <div class="cf">${WEEKS.map(w => `<div class="cw" title="${w[0]}: in ${w[1]}k · out ${w[2]}k"><div class="cb"><i style="height:${w[1] / mx * 100}%;background:var(--g6)"></i><i style="height:${w[2] / mx * 100}%;background:#e9b872"></i></div><small>${w[0]}</small></div>`).join('')}</div>
      <p class="hint" style="margin:10px 0 0">Week of 26 Oct is tight: AED 142k out (quarterly AMC + service charges) against 184k in.</p></section></div>
    <section class="pn mt"><div class="pn-h"><h2>Profit by listing & service</h2><span class="sub">Last 12 months · after direct costs</span><span class="sp"></span><a data-act="mTab" data-arg="Profit & loss">Full P&L ${ico('chevR')}</a></div>
      <table class="tbl"><thead><tr><th>Listing / service</th><th>Revenue</th><th>Direct costs</th><th>Profit</th><th style="width:220px">Margin</th></tr></thead><tbody>
      ${P.map(p => `<tr class="ck" data-go="portfolio"><td><div class="li"><img src="${p[2]}" alt=""><div><b>${esc(p[0])}</b><small>${esc(p[1])}</small></div></div></td><td>${aed(p[3])}</td><td>${aed(p[4])}</td><td><b>${aed(p[5])}</b></td><td><div class="qbar"><i style="--bw:140px;--w:${Math.round(p[6] * 100)}%;--c:${p[6] < .3 ? 'var(--amber)' : 'var(--g6)'}"></i><b style="font-size:13px;color:${p[6] < .3 ? 'var(--amber)' : 'var(--ink)'}">${Math.round(p[6] * 100)}%</b></div></td></tr>`).join('')}</tbody></table></section>`;
  }

  function tab(t) {
    if (t === 'Transactions') return `<section class="pn">${filt()}<div style="height:12px"></div><table class="tbl"><thead><tr><th>Date</th><th>Reference</th><th>Customer / payee</th><th>For</th><th>Pack · branch</th><th style="text-align:right">Amount</th><th>Status</th></tr></thead><tbody>${TX.map(r => `<tr class="ck" data-act="mTx" data-arg="${r[1]}"><td>${r[0]}</td><td><b>${r[1]}</b></td><td>${esc(r[2])}</td><td>${esc(r[3])}</td><td class="hint">${r[7]} · ${r[8]}</td><td style="text-align:right;font-weight:800;color:${r[4] === 'in' ? 'var(--g7)' : 'var(--ink)'}">${r[4] === 'in' ? '+' : '−'} ${aed(r[5])}</td><td>${st(r[6], stK(r[6]))}</td></tr>`).join('')}</tbody></table></section>`;
    if (t === 'Invoices') return `<div class="g4" style="margin-bottom:16px">${[['Sent this month', '214'], ['Paid', '188 · AED 486k'], ['Overdue', '17 · AED 88k'], ['Failed to send', '1']].map(k => `<div class="kpi" style="cursor:default"><small>${k[0]}</small><b style="font-size:22px">${k[1]}</b></div>`).join('')}</div><section class="pn">${filt()}<div style="height:12px"></div>${tbl(['Invoice', 'Customer', 'For', 'Issued', 'Due', 'Amount', 'Status'], [['INV-2026-0418', 'Aisha Al Mansoori', 'Rent Q4', '28 Sep', '1 Oct', 'AED 60,000', '§Paid'], ['INV-2026-0416', 'Omar Hassan', 'Rent · cheque 2', '20 Sep', '23 Sep', 'AED 29,500', '§Bounced|risk'], ['INV-2026-0412', 'Hassan Ali', 'Venue deposit', '18 Sep', '25 Sep', 'AED 3,600', '§Failed to send|warn'], ['INV-2026-0409', 'Tom Evans', 'AC servicing', '17 Sep', '24 Sep', 'AED 447', '§Overdue|risk'], ['INV-2026-0402', 'Mei Lin', 'Padel · October', '15 Sep', '1 Oct', 'AED 1,760', '§Sent|info']])}</section>`;
    if (t === 'Bills') return `<div class="g4" style="margin-bottom:16px">${[['To approve', '3 · AED 4,150'], ['Scheduled', 'AED 12,400 · Wed'], ['Owed to suppliers', 'AED 64,250'], ['Owed to UpNow', 'AED 1,500 · credit applied']].map(k => `<div class="kpi" style="cursor:default"><small>${k[0]}</small><b style="font-size:20px">${k[1]}</b></div>`).join('')}</div><section class="pn"><div class="pn-h"><h2>Supplier bills & purchase orders</h2><span class="sp"></span><button class="btn btn-g btn-sm" data-act="toastX" data-arg="New bill form opened">${ico('plus')}Add bill</button></div>${tbl(['Bill / PO', 'Supplier', 'For', 'Amount', 'Due', 'Status', ''], [['BIL-441', 'CoolTech LLC', 'AC repair · A-0803', 'AED 1,850', '30 Sep', '§Awaiting approval|warn', `<button class="btn btn-g btn-sm" data-act="toastX" data-arg="Bill approved">Approve</button>`], ['BIL-440', 'KeyMaster', 'Lock change · B-0602', 'AED 650', '2 Oct', '§Awaiting approval|warn', `<button class="btn btn-g btn-sm" data-act="toastX" data-arg="Bill approved">Approve</button>`], ['PO-2211', 'Dubai Pest Control', 'Quarterly visit', 'AED 1,650', '3 Oct', '§Awaiting approval|warn', `<button class="btn btn-g btn-sm" data-act="toastX" data-arg="Bill approved">Approve</button>`], ['BIL-438', 'Sparkle Facilities', 'Move-out clean · B-0602', 'AED 650', 'Paid', '§Paid', ''], ['UPN-0926', 'UpNow', 'OS + marketplace · Sep', 'AED 1,500', '—', '§Launch credit|info', '']])}</section>`;
    if (t === 'Payouts') return `<section class="pn"><div class="pn-h"><h2>Payouts from UpNow</h2><span class="sub">Weekly on Wednesday · to AE07 •••• 4410</span><span class="sp"></span><button class="btn btn-o btn-sm" data-act="setTabGo" data-arg="Finance, Tax & Banking">Payout settings</button></div>${tbl(['Payout', 'Period', 'Payments', 'Fees', 'Net', 'Arrives', 'Status'], [['PAYOUT-40', '23–29 Sep', '41', 'AED 0', 'AED 184,600', 'Wed 30 Sep', '§Scheduled|info'], ['PAYOUT-39', '16–22 Sep', '38', 'AED 0', 'AED 142,300', '23 Sep', '§Paid'], ['PAYOUT-38', '9–15 Sep', '44', 'AED 0', 'AED 201,850', '16 Sep', '§Paid'], ['PAYOUT-37', '2–8 Sep', '36', 'AED 0', 'AED 118,400', '9 Sep', '§Paid']])}<p class="hint" style="margin:12px 0 0">Launch mode: UpNow fees are calculated but credited back in full.</p></section>`;
    if (t === 'Deposits') return `<div class="g4" style="margin-bottom:16px">${[['Held', 'AED 520,000'], ['Customers', '103'], ['Due back in 60 days', 'AED 48,000 · 9'], ['Disputed', '1']].map(k => `<div class="kpi" style="cursor:default"><small>${k[0]}</small><b style="font-size:22px">${k[1]}</b></div>`).join('')}</div><section class="pn"><div class="pn-h"><h2>Customer deposits</h2><span class="sub">Held in a separate protected ledger</span></div>${tbl(['Customer', 'Listing', 'Amount', 'Held since', 'Release', 'Status'], [['Aisha Al Mansoori', 'Avenue Residence · A-1204', 'AED 6,000', 'Oct 2025', 'Oct 2026', '§Renewal due|warn'], ['Layla Rahman', 'Marina Gate · 1807', 'AED 4,750', 'Sep 2026', 'Sep 2027', '§Held'], ['Priya Menon', 'Business Bay loft', 'AED 6,000', 'Jun 2026', 'Refunded 25 Sep', '§Released|mute'], ['Hassan Ali', 'Marina rooftop venue', 'AED 3,600', 'Sep 2026', '23 Oct', '§Held'], ['Nadia Trading LLC', 'Avenue Warehouse · WH-03', 'AED 12,000', 'Jan 2026', 'Jan 2027', '§Disputed|risk']])}</section>`;
    if (t === 'Expenses') return `<section class="pn"><div class="pn-h"><h2>Assets & recurring expenses</h2><span class="sub">AED 18,700 / month</span><span class="sp"></span><button class="btn btn-g btn-sm" data-act="toastX" data-arg="New expense form opened">${ico('plus')}Add expense</button></div>${tbl(['Item', 'Type', 'Branch', 'Monthly', 'Next due', 'Status'], [['Office · Business Bay', 'Rent', 'Dubai', 'AED 14,000', '1 Oct', '§Scheduled|info'], ['Service van · D 48213', 'Vehicle', 'Dubai', 'AED 3,200', '5 Oct', '§Active'], ['Cleaning equipment ×3', 'Equipment', 'Dubai', 'AED 400', '—', '§Active'], ['Software & phones', 'Overhead', 'All', 'AED 1,100', '12 Oct', '§Active']])}</section>`;
    if (t === 'Profit & loss') return `<section class="pn">${filt()}<div style="height:12px"></div><table class="tbl"><thead><tr><th>Line</th><th style="text-align:right">September</th><th style="text-align:right">August</th><th style="text-align:right">Change</th></tr></thead><tbody>${[['Revenue', 578400, 531200], ['Direct costs', -212600, -198300], ['Gross profit', 365800, 332900, 1], ['Overheads', -124100, -121800], ['UpNow charges', 0, 0], ['Operating profit', 241700, 211100, 1]].map(r => `<tr style="${r[3] ? 'background:var(--g1)' : ''}"><td>${r[3] ? `<b>${r[0]}</b>` : r[0]}</td><td style="text-align:right;${r[3] ? 'font-weight:800' : ''}">${r[1] < 0 ? '−' : ''}${aed(Math.abs(r[1]))}</td><td style="text-align:right" class="hint">${r[2] < 0 ? '−' : ''}${aed(Math.abs(r[2]))}</td><td style="text-align:right;font-weight:700;color:${r[2] && Math.abs(r[1]) >= Math.abs(r[2]) === r[1] > 0 ? 'var(--g7)' : 'var(--ink3)'}">${r[2] ? ((Math.abs(r[1]) / Math.abs(r[2]) - 1) * 100).toFixed(1) + '%' : 'Launch credit'}</td></tr>`).join('')}</tbody></table></section>`;
    return overview();
  }

  PWA.pages.finance = () => { const t = TABS.includes(S.finTab) ? S.finTab : 'Overview';
    return PWA.head('Money', 'Cash in and out, bills, payouts, deposits and profit — in one place.', `<button class="btn btn-o btn-sm" data-act="toastX" data-arg="Statement exported">Export statement</button><button class="btn btn-g btn-sm" data-act="mNew">${ico('plus')}New</button>`) +
      `<div class="tabs">${TABS.map(x => `<button class="${x === t ? 'on' : ''}" data-act="mTab" data-arg="${esc(x)}">${esc(x)}${x === 'Bills' ? '<span class="c">3</span>' : x === 'Invoices' ? '<span class="c">17</span>' : ''}</button>`).join('')}</div>` + tab(t); };
  PWA.pages.business = PWA.pages.finance;
  PWA.acts.mTab = t => { S.finTab = t; save(); render(); };
  PWA.acts.finTab = PWA.acts.mTab;
  PWA.acts.mAct = i => { const a = ACTN[+i]; const el = document.getElementById('ma' + i); if (el) { el.style.opacity = '.45'; el.querySelector('button').outerHTML = st('Done'); } toast(a[4]); };
  PWA.acts.mTx = ref => { const r = TX.find(x => x[1] === ref); drawer(`<div class="dr-h"><div style="flex:1"><h3>${esc(r[1])}</h3><small>${esc(r[3])} · ${r[0]}</small></div><button class="x" data-act="closeDrawer">${ico('x')}</button></div>
    <div class="dr-b"><div style="font-size:30px;font-weight:800;color:${r[4] === 'in' ? 'var(--g7)' : 'var(--ink)'}">${r[4] === 'in' ? '+' : '−'} ${aed(r[5])}</div>${st(r[6], stK(r[6]))}
    <div class="kv"><div><span>${r[4] === 'in' ? 'From' : 'To'}</span><b>${esc(r[2])}</b></div><div><span>Pack · branch</span><b>${r[7]} · ${r[8]}</b></div><div><span>Method</span><b>${/cheque/.test(r[3]) ? 'Cheque' : 'Bank transfer'}</b></div><div><span>Matched to</span><b>${/Rent/.test(r[3]) ? 'Lease record' : 'Booking / job'}</b></div></div>
    <div class="sect-t">History</div><div class="ar">${ico('clock')}<div class="bd"><b style="font-weight:600">Created</b><small>${r[0]} · automatically</small></div></div><div class="ar">${ico('check')}<div class="bd"><b style="font-weight:600">${esc(r[6])}</b><small>${r[0]}</small></div></div></div>
    <div class="dr-f"><button class="btn btn-o btn-sm" data-act="toastX" data-arg="Receipt downloaded">${ico('file')}Receipt</button>${r[6] === 'Bounced' ? `<button class="btn btn-g btn-sm" data-act="toastX" data-arg="Formal notice sent">Send notice</button>` : ''}</div>`); };
  PWA.acts.mNew = () => modal(`<div class="mh"><h3>New</h3><button class="x" data-act="closeModal">${ico('x')}</button></div><div class="mb"><div class="opts" style="grid-template-columns:1fr 1fr">${[['Invoice', 'Bill a customer'], ['Payment received', 'Record cash, cheque or transfer'], ['Supplier bill', 'Something you owe'], ['Expense', 'Recurring or one-off cost']].map(x => `<button class="opt txt" data-act="mNewGo" data-arg="${x[0]}"><b>${x[0]}</b><small>${x[1]}</small></button>`).join('')}</div></div>`);
  PWA.acts.mNewGo = x => { closeModal(); toast(x + ' form opened'); };
  PWA.acts.setTabGo = t => { S.setTab = t; save(); go('settings'); };

  /* Vendors → pack Operations */
  const baseOps = PWA.pages.ops;
  PWA.pages.ops = () => baseOps() + `<section class="pn mt"><div class="pn-h"><h2>Vendors & contracts</h2><span class="sub">Suppliers who deliver ${esc(PKL(S.pack).toLowerCase())} work</span><span class="sp"></span><button class="btn btn-g btn-sm" data-act="toastX" data-arg="Vendor invite opened">${ico('plus')}Add vendor</button></div>
    ${PWA.tbl(['Vendor', 'Category', 'Contract', 'Renewal', 'SLA', 'Open bills', 'Status'], [['CoolTech LLC', 'AC maintenance', 'AMC · AED 48k / yr', '12 Jan 2027', '89%', 'AED 1,850', '§Below SLA|warn'], ['Sparkle Facilities', 'Cleaning', 'Per job', '—', '96%', '—', '§Active'], ['KeyMaster', 'Locksmith', 'On call', '—', '98%', 'AED 650', '§Active'], ['Dubai Pest Control', 'Pest control', 'Quarterly · AED 6k', '3 Mar 2027', '100%', 'AED 1,650', '§Active']])}</section>`;
})();
