/* Shared UpNow OS (Finance, Business, Settings + channel activation) and vertical packs (all 7) */
(function () {
  const { ico, esc, av, aed, st, S, save, toast, modal, closeModal, drawer, go, render, pop, closePop, PK, PKL, PKI, packNav } = PWA;
  const tbl = (h, rows, ck) => `<table class="tbl"><thead><tr>${h.map(x => `<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r => `<tr ${ck ? `class="ck" data-act="${ck}"` : ''}>${r.map((c, i) => `<td>${String(c).startsWith('§') ? (([t, k]) => st(t, k))(c.slice(1).split('|')) : i === 0 ? `<b>${c}</b>` : c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  const head = (t, p, acts = '') => `<div class="ph"><div><div class="hint" style="font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:var(--g7);font-size:11px">${S.page && ['overview', 'portfolio', 'deals', 'ops', 'perf', 'cases', 'reports'].includes(S.page) ? esc(PKL(S.pack)) + ' pack' : 'Shared UpNow OS'}</div><h1>${t}</h1>${p ? `<p>${p}</p>` : ''}</div><span class="sp"></span><div class="acts">${acts}</div></div>`;
  const tabsUI = (list, cur, act) => `<div class="tabs">${list.map(x => `<button class="${x === cur ? 'on' : ''}" data-act="${act}" data-arg="${esc(x)}">${esc(x)}</button>`).join('')}</div>`;
  PWA.tbl = tbl; PWA.head = head;

  /* ============ PACK SWITCHER ============ */
  const VDESC = { spaces: 'Homes, stays, venues, courts, yachts', services: 'Cleaning, AC, salons, clinics', experiences: 'Safaris, workshops, tours', memberships: 'Gyms, clubs, credit packages', programs: 'Schools, courses, camps, academies', health: 'Clinics, practitioners, diagnostics', insurance: 'Motor, health, property cover' };
  PWA.acts.packMenu = (a, el) => {
    const r = el.getBoundingClientRect();
    const all = Object.keys(PK);
    pop(`<div class="pkm"><div class="h">Active packs</div>${all.filter(v => S.active.includes(v)).map(v => `<button class="r ${S.pack === v ? 'on' : ''}" data-v="${v}"><span class="ic">${ico(PKI[v])}</span><span class="bd"><b>${PKL(v)}</b><small>${VDESC[v]}</small></span>${S.pack === v ? ico('check') : ''}</button>`).join('')}
      <div class="h" style="margin-top:6px">Add a vertical</div>${all.filter(v => !S.active.includes(v)).map(v => `<button class="r" data-act="activatePack" data-arg="${v}"><span class="ic off">${ico(PKI[v])}</span><span class="bd"><b>${PKL(v)}</b><small>${VDESC[v]}</small></span><span class="st mute">Activate</span></button>`).join('') || '<p class="hint" style="padding:0 10px">All verticals active.</p>'}
      <p class="hint" style="padding:8px 10px 4px;margin:0;border-top:1px solid var(--line)">The shared OS is paid once. Each pack adds its own catalogue, records, licences and rules.</p></div>`, r.right + 8, r.top - 40);
    PWA.$('#pop').style.width = '340px'; PWA.$('#pop').style.padding = '0';
  };
  PWA.acts.activatePack = v => {
    closePop();
    const docs = { spaces: 'RERA / DTCM permit', services: 'Trade licence activity', experiences: 'DET tour operator licence', memberships: 'Facility / sports licence', programs: 'KHDA approval', health: 'DHA facility licence', insurance: 'CBUAE broker licence' }[v];
    modal(`<div class="mh"><span class="ic" style="width:40px;height:40px;border-radius:11px;background:var(--g1);color:var(--g7);display:grid;place-items:center">${ico(PKI[v])}</span><div style="flex:1"><h3>Activate ${PKL(v)} pack</h3><small class="hint">${VDESC[v]}</small></div><button class="x" data-act="closeModal">${ico('x')}</button></div><div class="mb">
      <div class="sect-t" style="margin-top:0">What you get</div><div class="chipset">${(PACKS.nav[PK[v]] || []).slice(1).map(x => `<span class="chip" style="height:28px;font-size:12px">${esc(x)}</span>`).join('')}</div>
      <div class="sect-t">Choose categories</div><div class="chipset">${(UP.VERTICALS[v] ? UP.VERTICALS[v].offers.map(o => o.label) : []).map((x, i) => `<button class="chip ${i === 0 ? 'on' : ''}" onclick="this.classList.toggle('on')">${esc(x)}</button>`).join('')}</div>
      <div class="sect-t">Required before publishing</div>
      <div class="ar">${ico('shield')}<div class="bd"><b>Business verification</b><small>Already verified for Greenstone</small></div>${st('Done')}</div>
      <div class="ar">${ico('file')}<div class="bd"><b>${docs}</b><small>Upload now or later — you can set up the pack while it is reviewed</small></div><button class="btn btn-o btn-sm" onclick="this.outerHTML='<span class=\\'st warn\\'>Uploaded</span>'">Upload</button></div>
      <div class="callout" style="margin:14px 0;padding:12px;border-radius:12px;background:var(--g1);font-size:12.5px"><b>Launch mode:</b> no subscription fee. Published pricing is calculated in shadow with a 100% launch credit.</div>
      <button class="btn btn-g" style="width:100%" data-act="packOn" data-arg="${v}">Activate ${PKL(v)}</button></div>`);
  };
  PWA.acts.packOn = v => { if (!S.active.includes(v)) S.active.push(v); S.pack = v; if (PW.V[v]) S.v = v; S.page = 'overview'; save(); closeModal(); render(); toast(PKL(v) + ' pack activated'); };

  /* ============ FINANCE ============ */
  PWA.pages.finance = () => { const t = S.finTab || 'Overview'; const tabs = ['Overview', 'Money in', 'Money out', 'UpNow charges', 'Refunds', 'Deposits', 'Invoices', 'Ledger'];
    const led = [['27 Sep', 'PAY-8901', 'Aisha → Greenstone', 'Rent payment', 'AED 30,000', '§Received'], ['27 Sep', 'VND-441', 'Greenstone → CoolTech', 'Maintenance', 'AED 1,850', '§Approval|warn'], ['26 Sep', 'UPN-0926', 'Greenstone → UpNow', 'OS + marketplace', 'AED 1,500', '§Credit applied'], ['25 Sep', 'REF-104', 'Greenstone → Customer', 'Deposit refund', 'AED 6,000', '§Paid'], ['24 Sep', 'JOB-5490', 'Yousef → Greenstone', 'AC service', 'AED 298', '§Received'], ['23 Sep', 'PAY-8870', 'Omar → Greenstone', 'Cheque 2 of 4', 'AED 29,500', '§Bounced|risk']];
    const f = { 'Money in': r => r[2].endsWith('Greenstone'), 'Money out': r => r[2].startsWith('Greenstone') && !r[2].includes('UpNow'), 'UpNow charges': r => r[2].includes('UpNow'), Refunds: r => /refund/i.test(r[3]), Deposits: r => /deposit/i.test(r[3]) }[t] || (() => 1);
    return head('Finance', 'Receivables, payouts, supplier payables, UpNow charges, refunds and held deposits.', `<button class="btn btn-o btn-sm" data-act="toastX" data-arg="Statement exported">Export</button><button class="btn btn-g btn-sm" data-act="toastX" data-arg="New payment record opened">${ico('plus')}New record</button>`) + tabsUI(tabs, t, 'finTab') +
      (t === 'Overview' ? `<div class="mcards">${[['Customers owe you', 'AED 369,380', 'Receivables', '17 overdue payments'], ['UpNow will pay you', 'AED 184,600', 'Next payout', 'Settlement due 30 Sep'], ['You owe suppliers', 'AED 64,250', 'Provider payables', 'Maintenance and AMC vendors'], ['You owe UpNow', 'AED 1,500', 'Platform charges', 'Launch credit applied: AED 4,850'], ['Refunds to customers', 'AED 8,200', 'Pending refunds', '3 approvals required'], ['Customer deposits held', 'AED 520,000', 'Protected liabilities', '103 active relationships']].map(m => `<div class="mc"><small>${m[0]}</small><strong>${m[1]}</strong><b>${m[2]}</b><div>${m[3]}</div></div>`).join('')}</div>` : '') +
      `<section class="pn mt"><div class="pn-h"><h2>${t === 'Overview' ? 'Recent ledger' : t}</h2></div>${tbl(['Date', 'Reference', 'From → To', 'Type', 'Amount', 'Status'], led.filter(f))}</section>`; };
  PWA.acts.finTab = t => { S.finTab = t; save(); render(); };
  PWA.acts.toastX = m => toast(m);

  /* ============ BUSINESS ============ */
  PWA.pages.business = () => { const t = S.bizTab || 'Entities & Branches'; const tabs = ['Entities & Branches', 'Vendors & Contracts', 'Purchases & Payables', 'People', 'Assets & Expenses', 'P&L'];
    const B = {
      'Entities & Branches': `<div class="g4">${[['Provider account', 'Greenstone Group', 'Owner: Khalid'], ['Legal entities', '2', 'UAE · Oman'], ['Operating branches', '3', 'Dubai · Abu Dhabi · Muscat'], ['Countries', '2', 'AED · OMR']].map(k => `<div class="kpi"><small>${k[0]}</small><b style="font-size:20px">${k[1]}</b><span class="d" style="color:var(--ink3)">${k[2]}</span></div>`).join('')}</div>
        <section class="pn mt"><div class="pn-h"><h2>Account structure</h2><span class="sp"></span><button class="btn btn-g btn-sm" data-act="toastX" data-arg="Entity form opened">${ico('plus')}Add entity or branch</button></div><div class="wf">${['UpNow account', 'Legal entity', 'Branch / location', 'Vertical pack', 'Offerings'].map(x => `<div class="d">${x}</div>`).join('')}</div>
        ${tbl(['Legal entity', 'Branch / service area', 'Country', 'Verticals', 'Tax & currency', 'Status'], [['Greenstone Services LLC', 'Dubai · group head office', 'UAE', 'Spaces · Services', 'VAT 5% · AED', '§Live'], ['Greenstone Services LLC', 'Abu Dhabi branch', 'UAE', 'Spaces', 'VAT 5% · AED', '§Setup|warn'], ['Greenstone Oman SPC', 'Muscat service area', 'Oman', 'Services', 'VAT 5% · OMR', '§Draft|mute']])}</section>`,
      'Vendors & Contracts': `<section class="pn">${tbl(['Vendor', 'Category', 'Contract', 'Renewal', 'SLA', 'Status'], [['CoolTech LLC', 'AC maintenance', 'AMC · AED 48k / yr', '12 Jan 2027', '89%', '§Below SLA|warn'], ['Sparkle Facilities', 'Cleaning', 'Per job', '—', '96%', '§Active'], ['KeyMaster', 'Locksmith', 'On call', '—', '98%', '§Active'], ['Dubai Pest Control', 'Pest control', 'Quarterly · AED 6k', '3 Mar 2027', '100%', '§Active']])}</section>`,
      'Purchases & Payables': `<section class="pn">${tbl(['PO', 'Vendor', 'For', 'Amount', 'Due', 'Status'], [['PO-2211', 'CoolTech LLC', 'Avenue Residence · A-0803', 'AED 1,850', '30 Sep', '§Approval|warn'], ['PO-2208', 'Sparkle Facilities', 'Move-out clean · B-0602', 'AED 650', '2 Oct', '§Approved'], ['PO-2201', 'Dubai Pest Control', 'Quarterly visit', 'AED 1,500', 'Paid', '§Paid']])}</section>`,
      People: `<section class="pn">${tbl(['Person', 'Role', 'Branch', 'Work mode', 'Capacity', 'Status'], [...PW.TEAM.spaces, ...PW.TEAM.services.slice(1)].map(t => [t[0], t[1], t[2], /tech|lead|stylist/i.test(t[1]) ? 'On-ground' : 'Remote + on-ground', '38h / 40h', '§' + t[4]]))}</section>`,
      'Assets & Expenses': `<section class="pn">${tbl(['Asset / expense', 'Type', 'Branch', 'Monthly cost', 'Status'], [['Service van · D 48213', 'Vehicle', 'Dubai', 'AED 3,200', '§Active'], ['Cleaning equipment set ×3', 'Equipment', 'Dubai', 'AED 400', '§Active'], ['Office · Business Bay', 'Rent', 'Dubai', 'AED 14,000', '§Active'], ['Software & phones', 'Overhead', 'All', 'AED 1,100', '§Active']])}</section>`,
      'P&L': `<section class="pn">${tbl(['Line', 'This month', 'Last month', 'Change'], [['Revenue', 'AED 578,400', 'AED 531,200', '+8.9%'], ['Direct costs', 'AED 212,600', 'AED 198,300', '+7.2%'], ['Gross margin', 'AED 365,800', 'AED 332,900', '+9.9%'], ['Overheads', 'AED 124,100', 'AED 121,800', '+1.9%'], ['UpNow charges', 'AED 0', 'AED 0', 'Launch credit'], ['Operating profit', 'AED 241,700', 'AED 211,100', '+14.5%']])}</section>`
    };
    return head('Business', 'Entities, branches, vendors, people, assets and P&L.') + tabsUI(tabs, t, 'bizTab') + B[t]; };
  PWA.acts.bizTab = t => { S.bizTab = t; save(); render(); };

  /* ============ SETTINGS ============ */
  const SGROUPS = () => [
    ['Business', [['Account & KYC', 'Legal identity, authorized signatory and verification documents', 'shield'], ['Entities & Branches', 'Legal entities, branches, countries and currencies', 'building'], ['Team & Permissions', 'Who can see and do what', 'users']]],
    ['Customers', [['Channels', 'Where leads come from and how they connect to your inbox', 'link'], ['Notifications', 'Who gets alerted, how, and when it escalates', 'bell'], ['Language', 'Workspace, listing and template languages', 'globe']]],
    ['Money', [['Finance, Tax & Banking', 'Payout accounts, VAT profile and invoice numbering', 'coin']]],
    ['Marketplace & rules', [['Marketplace Listings', 'Publication approval and attribution defaults', 'eye'], [PKL(S.pack) + ' Rules', 'Operating rules that apply only to ' + PKL(S.pack).toLowerCase(), 'layers'], ['Agentic Rules', 'Automations, owners and failure routes', 'zap']]]
  ];
  const STABS = () => ['Overview', ...SGROUPS().flatMap(g => g[1].map(x => x[0]))];
  const fld = (l, v = '', ph = '', type = 'input', opts) => `<div class="fld"><label>${l}</label>${type === 'sel' ? `<select>${(opts || [v]).map(o => `<option>${o}</option>`).join('')}</select>` : `<input ${type === 'date' ? 'type="date"' : ''} value="${esc(v)}" placeholder="${esc(ph)}">`}</div>`;
  const pn = (t, act, body, sub = '') => `<section class="pn"><div class="pn-h"><h2>${t}</h2>${sub ? `<span class="sub">${sub}</span>` : ''}<span class="sp"></span>${act}</div>${body}</section>`;
  const saveB = m => `<button class="btn btn-o btn-sm" data-act="toastX" data-arg="${m}">Save</button>`;

  const CH = [
    ['upnow', 'UpNow chat & calls', 'Built in', 'Leads from your UpNow listings: chat, call and request forms.', 'on', ['Built in — nothing to connect']],
    ['wa', 'WhatsApp Business', '+971 4 555 0198', 'Replies, templates and click-to-WhatsApp from listings.', 'on', ['Connect Meta Business account', 'Verify business number by OTP', 'Choose message templates', 'Route to team']],
    ['email', 'Email', 'leasing@greenstone.ae', 'Shared inbox. Enquiries are matched to leads automatically.', 'on', ['Connect Google or Microsoft 365 — or forward to your UpNow address', 'Pick inboxes to sync', 'Route to team']],
    ['phone', 'Tracked phone', '+971 4 555 0100', 'Tracked numbers per listing; calls are logged and recorded.', 'on', ['Choose a tracked number', 'Forward to your mobiles', 'Route to team']],
    ['ig', 'Instagram', '@greenstone.ae', 'DMs and ad lead forms with source attribution.', 'on', ['Log in with Meta', 'Pick the Instagram account', 'Route to team']],
    ['bayut', 'Bayut', 'Email parser', 'Import leads from your Bayut listings.', 'on', ['Enter your Bayut agent ID', 'Forward lead emails to your UpNow address', 'Map listings', 'Route to team']],
    ['pf', 'Property Finder', 'API', 'Import leads and calls from Property Finder.', 'on', ['Paste your Property Finder API key', 'Map listings', 'Route to team']],
    ['dubizzle', 'Dubizzle', '', 'Import chats and calls from your Dubizzle ads.', 'off', ['Enter your Dubizzle Pro account email', 'Forward lead emails to your UpNow address', 'Map listings', 'Route to team']],
    ['google', 'Google Business Profile', '', 'Messages and calls from Google Maps and Search.', 'off', ['Sign in with Google', 'Choose the business location', 'Route to team']],
    ['fb', 'Facebook', '', 'Page inbox and lead-ad forms.', 'off', ['Log in with Meta', 'Pick the page and lead forms', 'Route to team']],
    ['web', 'Website form', '', 'Embed an UpNow enquiry form on your website.', 'off', ['Choose form fields', 'Copy the embed code', 'Route to team']],
    ['sms', 'SMS', '', 'Two-way SMS for reminders and replies.', 'off', ['Choose a sender ID', 'Register with the TRA', 'Route to team']]
  ];
  PW.SOURCES.fb = PW.SOURCES.fb || { l: 'Facebook', s: 'Facebook', c: '#3b5bab' };
  PW.SOURCES.web = PW.SOURCES.web || { l: 'Website form', s: 'Website', c: '#46534c' };
  PW.SOURCES.sms = PW.SOURCES.sms || { l: 'SMS', s: 'SMS', c: '#7b877f' };
  const chOn = c => c[4] === 'on' || S.chOn[c[0]];

  const SB = {
    'Account & KYC': () => `<div class="g2" style="grid-template-columns:1.4fr 1fr">${pn('Provider identity', saveB('Provider identity saved'), `<div class="frm">${fld('Provider type', 'Company', '', 'sel', ['Company', 'Individual owner'])}${fld('Legal name', 'Greenstone Services LLC')}${fld('Registration / licence number', 'CN-2081142')}${fld('Tax registration number', '100384726100003')}${fld('Registered address', 'Business Bay, Dubai')}${fld('Legal-notices address', 'PO Box 118822, Dubai')}</div>`)}
      ${pn('Authorized signatory', `<button class="btn btn-o btn-sm" data-act="toastX" data-arg="Signatory invited">Invite</button>`, `<div class="frm">${fld('Name', 'Khalid Baalfalasi')}${fld('Email and phone', 'khalid@greenstone.ae')}${fld('Authority', '', '', 'sel', ['Authorized signatory', 'Power of attorney', 'Manager'])}${fld('Expiry', '2027-06-30', '', 'date')}</div>`)}</div>
      <div class="mt">${pn('Verification documents', '', tbl(['Document', 'Applies to', 'Expiry', 'Status', 'Action'], ['Trade licence / company registration', 'Owner or signatory identity', 'Passport and visa where required', 'VAT registration certificate', 'Power of attorney / signing authority', PKL(S.pack) + ' regulatory licence'].map((x, i) => [x, i === 5 ? PKL(S.pack) + ' / jurisdiction' : 'Provider account', i === 1 ? '—' : i === 5 ? '14 Oct 2026' : '15 Dec 2026', i === 5 ? '§Renewal due|warn' : '§Verified', `<button class="btn btn-o btn-sm" data-act="toastX" data-arg="Document manager opened">View / replace</button>`])), 'Business once · vertical licences only when required')}</div>`,
    'Entities & Branches': () => pn('Legal entities and operating branches', `<button class="btn btn-g btn-sm" data-act="toastX" data-arg="Entity or branch form opened">${ico('plus')}Add</button>`, tbl(['Entity / branch', 'Country', 'Currency & tax', 'Verticals', 'Listings & operations', 'Status'], [['Greenstone Services LLC<br><small class="hint">Legal entity</small>', 'UAE', 'AED · UAE VAT', 'Spaces · Services', 'Dubai and Abu Dhabi', '§Active'], ['Dubai Marina branch<br><small class="hint">Operating branch</small>', 'UAE', 'Inherited', 'Spaces', '9 properties · 113 units', '§Active'], ['Greenstone Oman SPC<br><small class="hint">Legal entity</small>', 'Oman', 'OMR · Oman VAT', 'Services', 'Muscat', '§Draft|mute']])),
    'Team & Permissions': () => pn('Team access', `<button class="btn btn-g btn-sm" data-act="invite">${ico('plus')}Invite member</button>`, tbl(['Member', 'Role', 'Branch / portfolio', 'Work modes', 'Sensitive access', 'Status'], [['Khalid Baalfalasi', 'Owner', 'All', 'Remote', 'Everything', '§Active'], ['Ahmed Karim', 'Leasing manager', 'Dubai Marina', 'Remote + on-ground', 'Customer records · operations', '§Active'], ['Sara Idris', 'Operations', 'Stays · venues', 'Remote + on-ground', 'Customer records', '§Active'], ['Finance controller', 'Finance', 'All UAE', 'Remote', 'Pay, cost, margin · banking', '§Active'], ['Rashid Omar', 'Technician', 'All Dubai', 'On-ground', 'Assigned work only', '§Active']])
      + `<p class="hint" style="margin:14px 0 0"><b>Permission boundary:</b> workers see assigned work. Managers see team delivery. Only owners and finance roles see pay, cost, banking and margin.</p>`),
    Channels: () => { const on = CH.filter(chOn), off = CH.filter(c => !chOn(c));
      return `<section class="pn"><div class="pn-h"><h2>Lead & communication channels</h2><span class="sub">${on.length} connected · everything lands in one inbox</span></div>
      <div class="flow4">${['Connect', 'Verify', 'Map listings', 'Route to team'].map(() => '<span class="on"></span>').join('')}</div>
      <div class="chg">${CH.map(c => { const o = chOn(c), s = PW.SOURCES[c[0]]; const n = PWA.leads().filter(l => l.src === c[0]).length; return `<div class="chc ${o ? '' : 'off'}"><div class="t"><span class="sw" style="width:34px;height:34px;border-radius:10px;display:grid;place-items:center;color:#fff;font-weight:800;font-size:12px;background:${o ? s.c : 'var(--line2)'}">${esc(s.s.slice(0, 2))}</span><b>${esc(c[1])}</b>${o ? st('Live') : st('Off', 'mute')}</div><small>${esc(c[3])}</small>
        ${o ? `<div class="m"><span>${esc(S.chOn[c[0]] ? 'Connected just now' : c[2])}</span><span>${n} leads · 30d</span></div><button class="btn btn-o btn-sm" data-act="chManage" data-arg="${c[0]}">Manage</button>` : `<button class="btn btn-g btn-sm" data-act="chConnect" data-arg="${c[0]}">${ico('link')}Connect</button>`}</div>`; }).join('')}</div></section>
      <section class="pn mt"><div class="pn-h"><h2>Notices and automation</h2><span class="sub">One audited communication timeline</span></div><div class="chipset">${['Conversation', 'Notification', 'Reminder', 'Announcement', 'Formal notice', 'Warning', 'Consent request', 'Emergency alert', 'Delivery status', 'Customer acknowledgement'].map(x => `<span class="chip" style="height:28px;font-size:12px">${x}</span>`).join('')}</div></section>`; },
    'Finance, Tax & Banking': () => `<div class="g2">${pn('Bank accounts and payout rules', `<button class="btn btn-g btn-sm" data-act="toastX" data-arg="Bank account form opened">${ico('plus')}Add account</button>`, `<div class="ar">${ico('coin')}<div class="bd"><b>Primary AED operating account</b><small>Verified IBAN AE07 •••• 4410 · provider payouts · UAE entity</small></div>${st('Primary')}</div><div class="ar">${ico('lock')}<div class="bd"><b>Deposit holding account</b><small>Separate held-money ledger</small></div>${st('Verified')}</div><div class="ar">${ico('cal')}<div class="bd"><b>Payout schedule</b><small>Weekly on Wednesday · minimum AED 500</small></div><button class="btn btn-ghost btn-sm" data-act="toastX" data-arg="Payout schedule opened">Edit</button></div>`)}
      ${pn('Tax and invoicing', saveB('Tax settings saved'), `<div class="frm">${fld('Country', '', '', 'sel', ['United Arab Emirates', 'Oman', 'Saudi Arabia'])}${fld('Tax profile', '', '', 'sel', ['VAT registered', 'Not registered'])}${fld('Default currency', '', '', 'sel', ['AED', 'OMR', 'SAR'])}${fld('Invoice numbering', 'INV-{YEAR}-{NUMBER}')}</div>`)}</div>`,
    Notifications: () => pn('Notification rules', saveB('Notification rules saved'), tbl(['Event', 'Owner', 'Channels', 'Escalation'], [['New lead or customer reply', 'Demand owner', 'In-app · email · WhatsApp', 'Manager after 15 min'], ['Viewing / appointment in 1 hour', 'Assignee', 'Push · WhatsApp', '—'], ['Payment due, failed or unmatched', 'Finance', 'In-app · email', 'Owner'], ['Work late or evidence missing', 'Accountable owner', 'Push · in-app', 'Operations lead'], ['Licence, agreement or AMC expiry', 'Compliance owner', 'Email · in-app', 'Provider owner']])),
    Language: () => pn('Languages and translated content', `<button class="btn btn-g btn-sm" data-act="toastX" data-arg="Language picker opened">${ico('plus')}Add language</button>`, tbl(['Language', 'Direction', 'Workspace', 'Listings', 'Templates', 'Status'], [['English', 'LTR', 'Complete', 'Required', 'Approved', '§Live'], ['العربية', 'RTL', 'Complete', 'Required', 'Approved', '§Live'], ['Русский', 'LTR', '—', 'Optional', '4 of 12', '§Draft|mute']])),
    'Marketplace Listings': () => pn('Listing and publication defaults', saveB('Marketplace defaults saved'), `<div class="opts" style="grid-template-columns:repeat(2,1fr)">${[['Manual approval', 'Every new listing and every changed version'], ['Hybrid inventory', 'Unique space or multiple identical units'], ['Provider chooses action', 'Contact, request approval or instant transaction'], ['Anonymous audience', 'Identity appears after contact, request, transaction or consent']].map(x => `<button class="opt txt on"><b>${x[0]}</b><small>${x[1]}</small></button>`).join('')}</div><div class="sect-t">Attribution captured</div><div class="chipset">${['First-touch source', 'Last-touch source', 'Tracked calls', 'WhatsApp clicks', 'Matched contacts', 'Audited corrections'].map(x => `<span class="chip" style="height:28px;font-size:12px">${x}</span>`).join('')}</div>`),
    'Agentic Rules': () => pn('Agentic operation', `<button class="btn btn-g btn-sm" data-act="toastX" data-arg="Automation rule builder opened">${ico('plus')}Add rule</button>`, tbl(['Trigger', 'Automatic action', 'Accountable owner', 'Human step', 'Failure route', 'Status'], [['New marketplace request', 'Create lead, enrich source, acknowledge', 'Demand owner', 'None', 'Manager after 10 min', '§On'], ['Viewing booked', 'Send pin, reminder 24 h + 1 h', 'Assignee', 'Log outcome', 'Manager', '§On'], ['Transfer received', 'Match amount and reference', 'Finance manager', 'Approve mismatch only', 'Finance exception', '§On'], ['SLA missed', 'Notify owner and reassign', 'Operations lead', 'Review', 'Group owner', '§On']]))
  };
  SB.rules = () => { const p = PKL(S.pack); if (S.pack === 'spaces') return `<div class="g2">${pn('Leasing and collection rules', saveB('Spaces rules saved'), `<div class="frm">${fld('Contract start days', '7')}${fld('Cheque due days', '5')}${fld('Allowed instalments', '1, 2, 4, 6, 12')}${fld('Rent VAT', '', '', 'sel', ['By property type and jurisdiction'])}${fld('Bounced cheque penalty', '', 'Fixed or percentage')}${fld('Cheque hold / replacement fee', '')}${fld('Early termination', '', 'Months, percentage or fixed')}${fld('Late renewal / move-out', '')}</div>`)}
      ${pn('Fees by property type', `<button class="btn btn-o btn-sm" data-act="toastX" data-arg="Fee table opened">Edit table</button>`, tbl(['Type', 'Registration', 'Admin', 'Commission', 'Deposit', 'Rent VAT'], ['Residential', 'Commercial', 'Industrial', 'Land'].map(x => [x, 'AED 220', 'AED 500', '5%', '5%', x === 'Residential' ? '0%' : '5%'])))}</div>
      <div class="g2 mt">${pn('Maintenance, restoration and AMC', '', `<div class="chipset">${['Coverage rules', 'Covered items', 'Customer responsibility', 'Restoration checklist', 'AMC categories', 'Visit frequency', 'Service-report evidence', 'Vendor assignment', 'Warranty and rework'].map(x => `<span class="chip" style="height:28px;font-size:12px">${x}</span>`).join('')}</div>`)}${pn('Legal periods and charges', '', `<div class="chipset">${['Reminder timing', 'Warning periods', 'Formal-notice method', 'Public-notary evidence', 'Case filing deadline', 'Legal costs', 'Enforcement records', 'Settlement approval', 'Deposit settlement'].map(x => `<span class="chip" style="height:28px;font-size:12px">${x}</span>`).join('')}</div>`)}</div>`;
    return pn(p + ' operating rules', saveB(p + ' rules saved'), `<div class="frm">${fld('Booking lead time', '24 hours')}${fld('Cancellation window', 'Free until 24 h before')}${fld('Deposit', '20% at confirmation')}${fld('No-show fee', '50%')}${fld('Reschedule limit', '2 per booking')}${fld('Evidence required on completion', '', '', 'sel', ['Photos + customer sign-off', 'Photos only', 'None'])}</div>`); };
  const ATTN = () => [
    ['Account & KYC', 'warn', PKL(S.pack) + ' regulatory licence renews 14 Oct', 'Renew'],
    ['Channels', 'info', CH.filter(c => !chOn(c)).length + ' lead channels not connected', 'Connect'],
    ['Entities & Branches', 'mute', 'Greenstone Oman SPC is still a draft', 'Finish'],
    ['Language', 'mute', 'Russian templates 4 of 12 translated', 'Review']
  ].filter(a => !(a[0] === 'Channels' && !CH.some(c => !chOn(c))));
  const SUMM = { 'Account & KYC': '5 of 6 documents verified', 'Entities & Branches': '2 entities · 3 branches', 'Team & Permissions': '5 members · 4 roles', Channels: () => CH.filter(chOn).length + ' of ' + CH.length + ' connected', Notifications: '5 rules active', Language: 'English · العربية', 'Finance, Tax & Banking': 'AED · VAT registered · weekly payouts', 'Marketplace Listings': 'Manual approval on', 'Agentic Rules': '4 automations on' };
  const summ = n => { const v = SUMM[n]; return typeof v === 'function' ? v() : v || 'Configured'; };
  const sOverview = () => { const A = ATTN(); return `
    <section class="pn"><div class="pn-h"><h2>Needs your attention</h2><span class="sub">${A.length} items</span></div>
      ${A.map(a => `<div class="ar"><span class="st ${a[1]}" style="width:10px;padding:0;height:10px"></span><div class="bd"><b>${esc(a[2])}</b><small>${esc(a[0])}</small></div><button class="btn btn-o btn-sm" data-act="setTab" data-arg="${esc(a[0])}">${a[3]}</button></div>`).join('')}</section>
    ${SGROUPS().map(([g, items]) => `<div class="sect-t" style="margin-top:22px">${g}</div><div class="sov">${items.map(([n, d, i]) => { const w = A.find(a => a[0] === n); return `<button class="soc" data-act="setTab" data-arg="${esc(n)}"><span class="ic">${ico(i)}</span><span class="bd"><b>${esc(n)}</b><small>${esc(d)}</small><em>${w ? `<span class="st ${w[1]}">${esc(w[3])} needed</span>` : `<span class="ok">${ico('check')}${esc(summ(n))}</span>`}</em></span>${ico('chevR')}</button>`; }).join('')}</div>`).join('')}`; };
  PWA.pages.settings = () => { let t = S.setTab; const tabs = STABS(); if (!tabs.includes(t)) t = 'Overview';
    const A = ATTN(); let meta = null, grp = '';
    SGROUPS().forEach(([g, items]) => items.forEach(x => { if (x[0] === t) { meta = x; grp = g; } }));
    const nav = `<aside class="snav"><label class="ssrch">${ico('search')}<input id="sSearch" placeholder="Search settings"></label>
      <a class="si ${t === 'Overview' ? 'on' : ''}" data-act="setTab" data-arg="Overview" data-k="overview">${ico('grid')}<span>Overview</span>${A.length ? `<em>${A.length}</em>` : ''}</a>
      ${SGROUPS().map(([g, items]) => `<div class="sg"><div class="sgl">${g}</div>${items.map(([n, d, i]) => `<a class="si ${t === n ? 'on' : ''}" data-act="setTab" data-arg="${esc(n)}" data-k="${esc((n + ' ' + d).toLowerCase())}">${ico(i)}<span>${esc(n)}</span>${A.find(a => a[0] === n && a[1] === 'warn') ? '<i class="dot"></i>' : ''}</a>`).join('')}</div>`).join('')}
      <p class="hint snone" style="display:none;padding:8px 10px">No settings match.</p></aside>`;
    const body = t === 'Overview' ? sOverview() : `<div class="shd"><span class="ic">${ico(meta[2])}</span><div><div class="crumb"><a data-act="setTab" data-arg="Overview">Settings</a> / ${esc(grp)}</div><h2>${esc(t)}</h2><p>${esc(meta[1])}</p></div></div>${(SB[t] || SB.rules)()}`;
    return head('Settings', 'Your business, customer channels, money and operating rules — grouped so you can find things fast.', `<span class="st mute" style="height:32px">${esc(PKL(S.pack))} · ${S.active.length} packs active</span>`) + `<div class="setg">${nav}<div class="smain">${body}</div></div>`; };
  PWA.after.settings = () => { const Q = s => [...document.querySelectorAll(s)]; const i = document.getElementById('sSearch'); if (!i) return; i.oninput = () => { const q = i.value.trim().toLowerCase(); let n = 0; Q('.snav .si').forEach(a => { const m = !q || a.dataset.k.includes(q); a.style.display = m ? '' : 'none'; if (m) n++; }); Q('.snav .sg').forEach(g => g.style.display = [...g.querySelectorAll('.si')].some(a => a.style.display !== 'none') ? '' : 'none'); document.querySelector('.snone').style.display = n ? 'none' : ''; }; };
  PWA.acts.setTab = t => { S.setTab = t; save(); render(); };
  PWA.openChannels = () => { S.setTab = 'Channels'; save(); go('settings'); };

  /* ---- channel activation wizard ---- */
  const CW = { k: null, step: 0 };
  PWA.acts.chConnect = k => { CW.k = k; CW.step = 0; chw(); };
  PWA.acts.chManage = k => { const c = CH.find(x => x[0] === k); const s = PW.SOURCES[k]; modal(`<div class="mh"><h3>${esc(c[1])}</h3><button class="x" data-act="closeModal">${ico('x')}</button></div><div class="mb">
    <div class="kv" style="margin-top:0"><div><span>Account</span><b>${esc(c[2] || 'Connected')}</b></div><div><span>Status</span><b style="color:var(--g7)">Healthy · synced 2 min ago</b></div><div><span>Leads (30 days)</span><b>${PWA.leads().filter(l => l.src === k).length * 10}</b></div><div><span>Routed to</span><b>Round-robin · Leasing team</b></div></div>
    <div class="chr"><div class="bd"><b>Auto-acknowledge new messages</b><small>Instant reply in the lead's language</small></div><span class="tog on" onclick="this.classList.toggle('on')" style="cursor:pointer"></span></div>
    <div class="chr"><div class="bd"><b>Create a lead from every new contact</b><small>Matched by phone / email first</small></div><span class="tog on" onclick="this.classList.toggle('on')" style="cursor:pointer"></span></div>
    <div style="display:flex;gap:8px;margin-top:14px"><button class="btn btn-o btn-sm" data-act="toastX" data-arg="Test message sent">Send test</button><span style="flex:1"></span>${c[4] !== 'on' || k !== 'upnow' ? `<button class="btn btn-ghost btn-sm" style="color:var(--red)" data-act="chOff" data-arg="${k}">Disconnect</button>` : ''}</div></div>`); };
  PWA.acts.chOff = k => { const c = CH.find(x => x[0] === k); if (k === 'upnow') return; c[4] = 'off'; delete S.chOn[k]; save(); closeModal(); render(); toast(c[1] + ' disconnected'); };
  function chw() {
    const c = CH.find(x => x[0] === CW.k), s = PW.SOURCES[CW.k], steps = c[5].concat(['Done']);
    const k = CW.k, i = CW.step, last = i === steps.length - 1;
    const addr = 'leads+greenstone@in.upnow.ae';
    const body = (() => {
      if (last) return `<div style="text-align:center;padding:20px 0"><div style="width:56px;height:56px;border-radius:50%;background:var(--g1);color:var(--g7);display:grid;place-items:center;margin:0 auto 12px">${ico('check')}</div><h3 style="font-family:var(--serif);font-weight:400;font-size:24px;color:var(--g9)">${esc(c[1])} is live</h3><p class="hint">New ${esc(s.s)} leads will appear in Leads and Communications, tagged with their source.</p></div>`;
      const t = steps[i];
      if (/Route/.test(t)) return `${fld('Assign new leads to', '', '', 'sel', ['Round-robin · whole team', 'Ahmed Karim', 'Sara Idris', 'Khalid Baalfalasi'])}${fld('Reply target', '', '', 'sel', ['15 minutes', '5 minutes', '30 minutes', '1 hour'])}<div class="chr"><div class="bd"><b>Instant auto-acknowledgement</b><small>“Thanks — a Greenstone agent will reply shortly.”</small></div><span class="tog on" onclick="this.classList.toggle('on')" style="cursor:pointer"></span></div>`;
      if (/Map listings/.test(t)) return `<p class="hint" style="margin-top:0">We found 6 listings on ${esc(s.s)}. Match them to UpNow listings so every lead knows which property it's about.</p>${PWA.listings().slice(0, 4).map((l, j) => `<div class="ar"><img src="${l.img}" style="width:44px;height:34px;border-radius:7px;object-fit:cover"><div class="bd"><b>${esc(s.s)} ref ${['BY-4411', 'BY-4502', 'BY-4618', 'BY-4720'][j]}</b><small>→ ${esc(l.t)}</small></div>${st(j < 3 ? 'Auto-matched' : 'Check', j < 3 ? '' : 'warn')}</div>`).join('')}`;
      if (/OTP/.test(t)) return `${fld('Business number', '+971 4 555 0198')}<p class="hint">We sent a 6-digit code by SMS to this number.</p><div style="display:flex;gap:8px">${[4, 8, 1, 9, 2, 6].map(n => `<input value="${n}" style="width:44px;height:48px;text-align:center;font-size:18px;font-weight:800;border:1.5px solid var(--line2);border-radius:10px">`).join('')}</div>`;
      if (/API key/.test(t)) return `${fld('API key', 'pf_live_•••••••••••••3a9c')}<p class="hint">Find it in Property Finder Pro → Settings → Integrations.</p>`;
      if (/forward/i.test(t)) return `<p class="hint" style="margin-top:0">Add this forwarding address in your ${esc(s.s)} account. Every lead email is turned into an UpNow lead within seconds.</p><div style="display:flex;gap:8px;align-items:center;background:var(--bg);border:1px dashed var(--line2);border-radius:10px;padding:12px"><b style="flex:1;font-family:monospace;font-size:13px">${addr}</b><button class="btn btn-o btn-sm" data-act="toastX" data-arg="Address copied">Copy</button></div>${k === 'email' ? `<div class="sect-t">Or connect directly</div><div style="display:flex;gap:8px"><button class="btn btn-o btn-sm" data-act="chNext">Google Workspace</button><button class="btn btn-o btn-sm" data-act="chNext">Microsoft 365</button></div>` : ''}`;
      if (/embed/.test(t)) return `<pre style="background:var(--g9);color:#d8efe3;padding:14px;border-radius:12px;font-size:12px;white-space:pre-wrap">&lt;script src="https://forms.upnow.ae/embed.js"\n  data-provider="greenstone" data-lang="auto"&gt;&lt;/script&gt;</pre><button class="btn btn-o btn-sm" data-act="toastX" data-arg="Embed code copied">Copy code</button>`;
      if (/tracked number|sender ID/i.test(t)) return `<div class="opts" style="grid-template-columns:1fr 1fr">${['+971 4 555 0100', '+971 4 555 0142', '+971 800 GREEN'].map((n, j) => `<button class="opt txt ${j === 0 ? 'on' : ''}" onclick="this.parentNode.querySelectorAll('.opt').forEach(o=>o.classList.remove('on'));this.classList.add('on')"><b>${n}</b><small>${j === 2 ? 'Toll-free' : 'Dubai landline'}</small></button>`).join('')}</div>`;
      if (/Log in|Sign in|Connect Meta|Connect Google/.test(t)) return `<div style="text-align:center;padding:14px 0"><div style="width:56px;height:56px;border-radius:14px;background:${s.c};color:#fff;display:grid;place-items:center;margin:0 auto 12px;font-weight:800">${esc(s.s.slice(0, 2))}</div><p class="hint">A secure ${esc(s.s)} window opens. Approve UpNow to read and reply to messages and lead forms.</p><button class="btn btn-g" data-act="chNext">${ico('lock')}Continue with ${/Google/.test(t) ? 'Google' : 'Meta'}</button></div>`;
      if (/Pick|Choose/.test(t)) return `<div class="opts" style="grid-template-columns:1fr">${['Greenstone Properties', 'Greenstone Services'].map((n, j) => `<button class="opt txt ${j === 0 ? 'on' : ''}" onclick="this.parentNode.querySelectorAll('.opt').forEach(o=>o.classList.remove('on'));this.classList.add('on')"><b>${n}</b><small>${j ? '1.2k followers' : '8.4k followers · verified'}</small></button>`).join('')}</div>`;
      if (/agent ID|account email/.test(t)) return fld(t.replace('Enter your ', '').replace(/^./, m => m.toUpperCase()), '', k === 'bayut' ? 'e.g. 118204' : 'you@greenstone.ae');
      if (/templates/.test(t)) return `<div class="chipset">${['Viewing confirmation', 'Reminder 24 h', 'Document request', 'Payment reminder', 'Welcome'].map(x => `<button class="chip on" onclick="this.classList.toggle('on')">${x}</button>`).join('')}</div><p class="hint">Templates are submitted to Meta for approval (usually minutes).</p>`;
      return `<p class="hint">${esc(t)}</p>`;
    })();
    modal(`<div class="mh"><span class="sw" style="width:38px;height:38px;border-radius:10px;display:grid;place-items:center;color:#fff;font-weight:800;font-size:12px;background:${s.c}">${esc(s.s.slice(0, 2))}</span><div style="flex:1"><h3>Connect ${esc(c[1])}</h3><small class="hint">Step ${Math.min(i + 1, steps.length - 1)} of ${steps.length - 1}${last ? '' : ' · ' + esc(steps[i])}</small></div><button class="x" data-act="closeModal">${ico('x')}</button></div>
      <div class="mb"><div class="flow4">${steps.slice(0, -1).map((_, j) => `<span class="${j <= i ? 'on' : ''}"></span>`).join('')}</div>${last ? '' : `<h4 style="margin:0 0 12px;font-size:15px">${esc(steps[i])}</h4>`}${body}
      <div style="display:flex;gap:8px;margin-top:18px">${i && !last ? `<button class="btn btn-o btn-sm" data-act="chBack">Back</button>` : ''}<span style="flex:1"></span><button class="btn btn-g btn-sm" data-act="${last ? 'chDone' : 'chNext'}">${last ? 'Go to inbox' : i === steps.length - 2 ? 'Activate channel' : 'Continue'}</button></div></div>`, 'lg');
  }
  PWA.acts.chNext = () => { const c = CH.find(x => x[0] === CW.k); CW.step = Math.min(CW.step + 1, c[5].length); if (CW.step === c[5].length) { S.chOn[CW.k] = 1; save(); render(); } chw(); };
  PWA.acts.chBack = () => { CW.step = Math.max(0, CW.step - 1); chw(); };
  PWA.acts.chDone = () => { closeModal(); S.inboxCh = CW.k; S.thread = null; save(); go('inbox'); toast(PW.SOURCES[CW.k].l + ' connected'); };
  PWA.acts.connect = k => PWA.acts.chConnect(k);

  /* ============ VERTICAL PACK PAGES ============ */
  const secs = name => ((PACKS.sec[PK[S.pack]] || {})[name]) || [];
  const offersOf = () => Object.entries((PACKS.offers[PK[S.pack]] || {}).offers || {});
  const modsGrid = name => `<div class="mods">${secs(name).map((m, i) => `<div class="md" data-act="toastX" data-arg="${esc(m)} opened"><span class="ic">${ico(['grid', 'layers', 'file', 'wrench', 'chart', 'alert', 'users', 'cal'][i % 8])}</span><div><b>${esc(m)}</b><small>${[12, 4, 28, 7, 3, 16, 9, 21, 5, 2, 11, 6][i % 12]} records · ${i % 3 ? 'up to date' : 'needs review'}</small></div></div>`).join('')}</div>`;
  const pnav = () => packNav();
  const nm = id => (pnav().find(x => x[0] === id) || [, id])[1];
  const isCore = () => ['spaces', 'services'].includes(S.pack);

  PWA.pages.overview = () => {
    const sp = S.pack === 'spaces', core = isCore();
    const s = sp ? [['Live marketplace', '8 listings', '1 awaiting approval'], ['Demand', '11 active leads', '3 require response'], ['Portfolio', '113 units', '92% occupied'], ['Exceptions', '9 open', '5 maintenance · 4 cases']] : [['Live marketplace', offersOf().length + ' offerings', 'All catalogue connected'], ['Demand', '12 active requests', '3 require response'], ["Today's delivery", '18 tasks', '15 within SLA'], ['Exceptions', '4 open', '1 escalated']];
    const [o0, of] = offersOf()[0] || ['', { flow: [] }];
    return head(`${PKL(S.pack)} command centre`, `Demand, operations, people and performance for your ${PKL(S.pack).toLowerCase()} business.`, `<button class="btn btn-g btn-sm" data-go="portfolio">${ico('plus')}${esc(nm('portfolio'))}</button>`) +
      `<div class="g4">${s.map(k => `<div class="kpi" data-go="${/Demand/.test(k[0]) ? 'leads' : /Exceptions/.test(k[0]) ? 'cases' : 'portfolio'}"><small>${k[0]}</small><b style="font-size:22px">${k[1]}</b><span class="d" style="color:var(--ink3)">${k[2]}</span></div>`).join('')}</div>
      <div class="g2 mt"><section class="pn"><div class="pn-h"><h2>Requires attention</h2><span class="sub">Across marketplace and operations</span></div>
        ${[['Respond to new ' + o0 + ' request', 'Marketplace lead · response SLA due soon', '12 min', 'leads'], ['Approve completed customer documents', 'Remote review · assigned to Operations Manager', 'Today', 'deals'], ['Resolve failed payment', 'Customer informed automatically · finance approval required', 'Overdue', 'finance'], ['Review on-ground completion', 'Technician uploaded evidence and customer sign-off', '2:30 PM', 'ops']].map(t => `<div class="ar" style="cursor:pointer" data-go="${t[3]}"><span class="st ${/Overdue|12/.test(t[2]) ? 'warn' : ''}" style="width:8px;padding:0;height:8px"></span><div class="bd"><b>${t[0]}</b><small>${t[1]}</small></div><span class="tmr ${/Overdue/.test(t[2]) ? '' : 'ok'}">${t[2]}</span></div>`).join('')}</section>
      <section class="pn"><div class="pn-h"><h2>Delivery today</h2><span class="sub">How work is being executed</span></div>${tbl(['Mode', 'Work', 'Within SLA', 'Exceptions'], [['Agentic', '32', '97%', '1'], ['Remote', '14', '93%', '2'], ['On-ground', '9', '89%', '2'], ['Hybrid', '6', '92%', '1']])}</section></div>
      <section class="pn mt"><div class="pn-h"><h2>Active workflow</h2><span class="sub">${esc(o0)} · one connected record</span></div><div class="wf">${of.flow.map((f, i) => `<div class="${i < 2 ? 'd' : i === 2 ? 'c' : ''}">${esc(f)}<small>${i < 2 ? 'Done' : i === 2 ? 'Current' : ''}</small></div>`).join('')}</div></section>
      <section class="pn mt"><div class="pn-h"><h2>Business performance</h2><span class="sub">Provider → branch → offering → transaction → task</span></div>${tbl(['Measure', 'Current', 'Target', 'Action'], [['Lead response', '8 min', 'Under 10 min', '§On track'], ['Task SLA', '92%', '95%', '§Improve|warn'], ['Capacity used', '78%', '75–85%', '§Healthy'], ['Rework', '3.8%', 'Below 3%', '§Review|warn'], ['Contribution margin', '41%', '40%', '§On track']])}</section>`;
  };

  // catalogue + transactions for non-core packs
  const basePortfolio = PWA.pages.portfolio, baseDeals = PWA.pages.deals;
  PWA.pages.portfolio = () => {
    if (isCore()) return basePortfolio();
    const n = nm('portfolio'), V = UP.VERTICALS[S.pack];
    return head(esc(n), `Offerings you publish on the UpNow marketplace.`, `<button class="btn btn-g btn-sm" data-act="toastX" data-arg="New offering wizard opened">${ico('plus')}Add offering</button>`) +
      `<div class="lgrid">${offersOf().map(([k, o], i) => { const vo = V && V.offers[i]; const img = vo && (vo.img[0] || vo.hero); return `<article class="lcard" data-act="toastX" data-arg="${esc(k)} opened"><div class="im">${img ? `<img src="${img}" alt="">` : `<div class="tile" style="--h:${150 + i * 40}"><b>${ico(PKI[S.pack])}</b><span>${esc(k)}</span></div>`}${st(i === 2 ? 'Draft' : 'Live', i === 2 ? 'mute' : '')}<span class="cat">${esc(k)}</span></div><div class="bd"><b class="t">${esc(k)} · Greenstone</b><span class="pr">${esc(o.basis)}</span><span class="hint">Customer action: <b>${esc(o.cta)}</b></span></div><div class="ms"><div><small>Views</small><b>${[1240, 860, 0, 420][i % 4]}</b></div><div><small>Leads</small><b>${[42, 28, 0, 11][i % 4]}</b></div><div><small>Quality</small><b>${[91, 84, 50, 77][i % 4]}</b></div></div></article>`; }).join('')}<button class="addc" data-act="toastX" data-arg="New offering wizard opened"><i>${ico('plus')}</i>Add offering</button></div>
      <div class="sect-t" style="margin-top:24px">${esc(n)} modules</div>${modsGrid(n)}`;
  };
  PWA.pages.deals = () => {
    if (isCore()) return baseDeals();
    const n = nm('deals'); const [o0, of] = offersOf()[0] || ['', { flow: [] }];
    return head(esc(n), `Customer records for ${PKL(S.pack).toLowerCase()} — from request to completion.`) + `<section class="pn"><div class="pn-h"><h2>Customer workflow</h2><span class="sub">${esc(o0)}</span></div><div class="wf">${of.flow.map((f, i) => `<div class="${i < 2 ? 'd' : i === 2 ? 'c' : ''}">${esc(f)}</div>`).join('')}</div></section><div class="sect-t" style="margin-top:20px">Modules</div>${modsGrid(n)}`;
  };
  PWA.pages.ops = () => { const n = nm('ops'); return head(esc(n), `${PKL(S.pack)} delivery — assignments, work orders, vendors and evidence.`) + `<div class="g4" style="margin-bottom:16px">${[['My work', '7 tasks', '2 on-ground'], ['Work orders', '14 open', '3 overdue'], ['Vendors', '18 active', '5 annual contracts'], ['SLA', '92%', 'Target 95%']].map(k => `<div class="kpi"><small>${k[0]}</small><b style="font-size:22px">${k[1]}</b><span class="d" style="color:var(--ink3)">${k[2]}</span></div>`).join('')}</div>` + modsGrid(n); };
  PWA.pages.perf = () => { const t = S.perfTab || 'Team'; return head('Performance & Economics', 'Expected versus delivered across people, agents and vendors.') + `<div class="g4" style="margin-bottom:16px">${[['Completed', '324'], ['Within SLA', '92%'], ['Revenue', 'AED 486k'], ['Contribution', '41%']].map(k => `<div class="kpi"><small>${k[0]}</small><b style="font-size:22px">${k[1]}</b></div>`).join('')}</div>` + tabsUI(['My Work', 'Team', 'Economics', 'Exceptions'], t, 'perfTab') +
    `<section class="pn">${t === 'Economics' ? tbl(['Task', 'Plan / actual', 'Labour', 'Vendor & materials', 'Revenue', 'Margin'], [['Customer qualification', '15m / 18m', 'AED 24', '—', 'AED 80', '70%'], [S.pack === 'spaces' ? 'Viewing & inspection' : 'Deliver service', '2h / 2h 20m', 'AED 180', 'AED 130', 'AED 520', '§40%|warn'], ['Quality verification', '10m / 12m', 'AED 16', '—', 'AED 50', '68%']])
      : t === 'Exceptions' ? [['Vendor Team A missed 3 requests', '89% SLA · 2 late arrivals · 1 rework', 'Reassign'], ['Ahmed above task-time standard', 'Viewing time is 17% above plan', 'Coach'], ['UpNow agent healthy', '145 of 148 actions completed · 3 exceptions routed', '98%']].map(x => `<div class="ar"><div class="bd"><b>${x[0]}</b><small>${x[1]}</small></div><button class="btn btn-o btn-sm" data-act="toastX" data-arg="${x[2]}">${x[2]}</button></div>`).join('')
      : tbl(['Person / executor', 'Expected', 'Capacity', 'Completed', 'SLA', 'Quality', 'Cost', 'Outcome'], [['Ahmed · Manager', '30 tasks · 95% SLA', '38h / 40h', '28', '94%', '4.8', 'AED 18.4k', '§On target'], ['Sara · Operations', '25 tasks · 95% SLA', '34h / 40h', '26', '97%', '4.7', 'AED 12.8k', '§On target'], ['Vendor Team A', '22 tasks · 92% SLA', 'Full', '19', '89%', '4.4', 'AED 9.2k', '§Below SLA|warn'], ['UpNow agent', '120 tasks', 'Unlimited', '118', '99%', '—', 'AED 0.6k', '§Ahead']].slice(t === 'My Work' ? 0 : 0, t === 'My Work' ? 1 : 4))}</section>`; };
  PWA.acts.perfTab = t => { S.perfTab = t; save(); render(); };
  PWA.pages.cases = () => { const n = nm('cases'), sp = S.pack === 'spaces'; return head(esc(n), '') + `<section class="pn"><div class="pn-h"><h2>Case stages</h2></div><div class="wf">${(sp ? ['Reminder', 'Warning', 'Formal notice', 'Case filed', 'Decision / settlement', 'Closed'] : ['Reported', 'Investigated', 'Action', 'Customer response', 'Resolution', 'Closed']).map((x, i) => `<div class="${i < 1 ? 'd' : i === 1 ? 'c' : ''}">${x}</div>`).join('')}</div></section>
    <section class="pn mt">${tbl(['Case', 'Customer', 'Related record', 'Owner', 'Stage', 'Next action'], [['CASE-241', 'Aisha Al Mansoori', 'AGR-2091 · active', 'Operations Manager', 'Warning', '§Customer acknowledgement|warn'], ['CASE-238', 'Omar Hassan', 'Bounced cheque 2 of 4', 'Finance Manager', 'Formal notice', '§Approve escalation|risk']])}</section><div class="sect-t" style="margin-top:20px">Case types</div>${modsGrid(n)}`; };
  PWA.pages.reports = () => { const t = S.repTab || 'Sales & conversion'; return head('Reports', `Shared reports plus ${PKL(S.pack).toLowerCase()}-specific operational reports.`, `<button class="btn btn-o btn-sm" data-act="toastX" data-arg="Report exported">Export report</button>`) + `<div class="fbar">${['Sales & conversion', 'Operations & SLA', 'Capacity & utilization', 'Performance & economics', 'Quality & rework', 'Customers', 'Cases'].map(x => `<button class="chip ${x === t ? 'on' : ''}" data-act="repTab" data-arg="${x}">${x}</button>`).join('')}</div>
    <section class="pn"><div class="pn-h"><h2>${esc(PKL(S.pack))} · ${esc(t)}</h2><span class="sub">Last 12 months</span></div><div class="g4">${[['Orders', '96', '+12%'], ['Revenue', 'AED 486k', '+9%'], ['SLA', '92%', 'Target 95%'], ['Margin', '41%', 'Target 40%']].map(k => `<div class="kpi"><small>${k[0]}</small><b style="font-size:22px">${k[1]}</b><span class="d">${k[2]}</span></div>`).join('')}</div>
    <div class="bars">${[40, 55, 48, 62, 70, 66, 78, 84, 80, 92, 88, 96].map(h => `<div style="height:${h}%"></div>`).join('')}</div><div style="display:flex;gap:10px;font-size:11px;color:var(--ink3);margin-top:6px">${['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'].map(m => `<span style="flex:1;text-align:center">${m}</span>`).join('')}</div></section>`; };
  const baseAdd = PWA.acts.addListing;
  PWA.acts.addListing = a => { if (isCore()) { if (S.v !== S.pack) S.v = S.pack; return baseAdd(a); } toast('New ' + PKL(S.pack).toLowerCase() + ' offering wizard opened'); go('portfolio'); };
  PWA.acts.repTab = t => { S.repTab = t; save(); render(); };
})();
